- name: installing mysql component
  hosts: mysql  
  become: yes
  tasks:
  - name: disabling myql 8
    command: yum module disable mysql -y 
  
  - name: copying mysql repo
    copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: installing mysql community server
    yum:
      name: mysql-community-server
      state: installed

  - name: enabling and starting mysql
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: We need to change the default root password in order to start using the database service. Use password RoboShop@1 or any other as per your choice.            
    command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: enabling and starting mysql
    service:
      name: mysqld
      state: restarted 